Update Brick: Change style confirm 3ds
paymentwall/module-woocommerce pull request #13
Opened 2017-01-16 05:27 UTC by doanhkaka

Update Brick: Change style confirm 3ds

2017-01-17 04:08 UTC, dzung2t commented on src/assets/js/payment.js
> +    }, showWaiting: function (message, type) {
Please refactor your codes

2017-01-17 05:47 UTC, dzungtran requested changes

2017-01-17 05:47 UTC, dzungtran commented on src/assets/js/payment.js
> +    }, showWaiting: function (message, type) {
Please refactor your codes

2017-01-19 12:03 UTC, dzungtran approved these changes

2017-01-19 12:04 UTC, merged